[project]
name = "bbi-streamlit-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<4.0"

dependencies = [
    "dhlab>=2.42.1,<3.0.0",
    "matplotlib",          # ingen hard versjon
    "pandas",
    "streamlit>=1.50.0",   # ny nok streamlit til å leke fint med Altair 6
]