[project]
name = "bbi-streamlit-app"
version = "0.1.0"
description = "BBI Streamlit app"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "dhlab>=2.42.1,<3.0.0",
    "jupyter>=1.1.1",
    "matplotlib",
    "pandas",
    "streamlit>=1.50.0",
]

[tool.poetry]
package-mode = false
